language: node_js
node_js: stable
install:
  - npm install
  - wget https://github.com/rust-lang/mdBook/releases/download/v0.3.7/mdbook-v0.3.7-x86_64-unknown-linux-gnu.tar.gz
  - tar -xzvf mdbook-*.tar.gz
script:
  - npm run -s build
  - npm run -s test
  - npm run -s example-all
  - ./mdbook build
before_deploy:
  openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv -in github_deploy_key.enc -out github_deploy_key -d
deploy:
  edge: true # use Travis-CI dpl v2
  provider: pages
  local_dir: book
  deploy_key: github_deploy_key
  on: # Todo - Just for testing - remove this before merge
    branch: travis-demo # Will default to master branch if on.branch is removed
